/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ButtonInput : TBase
  {
    private bool _down;
    private bool _justPressed;
    private bool _justReleased;

    public bool Down
    {
      get
      {
        return _down;
      }
      set
      {
        __isset.down = true;
        this._down = value;
      }
    }

    public bool JustPressed
    {
      get
      {
        return _justPressed;
      }
      set
      {
        __isset.justPressed = true;
        this._justPressed = value;
      }
    }

    public bool JustReleased
    {
      get
      {
        return _justReleased;
      }
      set
      {
        __isset.justReleased = true;
        this._justReleased = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool down;
      public bool justPressed;
      public bool justReleased;
    }

    public ButtonInput() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool) {
                Down = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Bool) {
                JustPressed = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Bool) {
                JustReleased = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ButtonInput");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.down) {
          field.Name = "down";
          field.Type = TType.Bool;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(Down);
          oprot.WriteFieldEnd();
        }
        if (__isset.justPressed) {
          field.Name = "justPressed";
          field.Type = TType.Bool;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(JustPressed);
          oprot.WriteFieldEnd();
        }
        if (__isset.justReleased) {
          field.Name = "justReleased";
          field.Type = TType.Bool;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(JustReleased);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ButtonInput(");
      bool __first = true;
      if (__isset.down) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Down: ");
        __sb.Append(Down);
      }
      if (__isset.justPressed) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("JustPressed: ");
        __sb.Append(JustPressed);
      }
      if (__isset.justReleased) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("JustReleased: ");
        __sb.Append(JustReleased);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
