/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ChefSpecificData : TBase
  {
    private int _highlightedForPickup;
    private int _highlightedForUse;
    private int _highlightedForPlacement;
    private double _dashTimer;
    private int _interactingEntity;
    private Point _lastVelocity;
    private bool _aimingThrow;
    private bool _movementInputSuppressed;
    private Point _lastMoveInputDirection;
    private double _impactStartTime;
    private double _impactTimer;
    private Point _impactVelocity;
    private double _leftOverTime;

    public int HighlightedForPickup
    {
      get
      {
        return _highlightedForPickup;
      }
      set
      {
        __isset.highlightedForPickup = true;
        this._highlightedForPickup = value;
      }
    }

    public int HighlightedForUse
    {
      get
      {
        return _highlightedForUse;
      }
      set
      {
        __isset.highlightedForUse = true;
        this._highlightedForUse = value;
      }
    }

    public int HighlightedForPlacement
    {
      get
      {
        return _highlightedForPlacement;
      }
      set
      {
        __isset.highlightedForPlacement = true;
        this._highlightedForPlacement = value;
      }
    }

    public double DashTimer
    {
      get
      {
        return _dashTimer;
      }
      set
      {
        __isset.dashTimer = true;
        this._dashTimer = value;
      }
    }

    public int InteractingEntity
    {
      get
      {
        return _interactingEntity;
      }
      set
      {
        __isset.interactingEntity = true;
        this._interactingEntity = value;
      }
    }

    public Point LastVelocity
    {
      get
      {
        return _lastVelocity;
      }
      set
      {
        __isset.lastVelocity = true;
        this._lastVelocity = value;
      }
    }

    public bool AimingThrow
    {
      get
      {
        return _aimingThrow;
      }
      set
      {
        __isset.aimingThrow = true;
        this._aimingThrow = value;
      }
    }

    public bool MovementInputSuppressed
    {
      get
      {
        return _movementInputSuppressed;
      }
      set
      {
        __isset.movementInputSuppressed = true;
        this._movementInputSuppressed = value;
      }
    }

    public Point LastMoveInputDirection
    {
      get
      {
        return _lastMoveInputDirection;
      }
      set
      {
        __isset.lastMoveInputDirection = true;
        this._lastMoveInputDirection = value;
      }
    }

    public double ImpactStartTime
    {
      get
      {
        return _impactStartTime;
      }
      set
      {
        __isset.impactStartTime = true;
        this._impactStartTime = value;
      }
    }

    public double ImpactTimer
    {
      get
      {
        return _impactTimer;
      }
      set
      {
        __isset.impactTimer = true;
        this._impactTimer = value;
      }
    }

    public Point ImpactVelocity
    {
      get
      {
        return _impactVelocity;
      }
      set
      {
        __isset.impactVelocity = true;
        this._impactVelocity = value;
      }
    }

    public double LeftOverTime
    {
      get
      {
        return _leftOverTime;
      }
      set
      {
        __isset.leftOverTime = true;
        this._leftOverTime = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool highlightedForPickup;
      public bool highlightedForUse;
      public bool highlightedForPlacement;
      public bool dashTimer;
      public bool interactingEntity;
      public bool lastVelocity;
      public bool aimingThrow;
      public bool movementInputSuppressed;
      public bool lastMoveInputDirection;
      public bool impactStartTime;
      public bool impactTimer;
      public bool impactVelocity;
      public bool leftOverTime;
    }

    public ChefSpecificData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 4:
              if (field.Type == TType.I32) {
                HighlightedForPickup = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.I32) {
                HighlightedForUse = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.I32) {
                HighlightedForPlacement = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 7:
              if (field.Type == TType.Double) {
                DashTimer = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 8:
              if (field.Type == TType.I32) {
                InteractingEntity = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 9:
              if (field.Type == TType.Struct) {
                LastVelocity = new Point();
                LastVelocity.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 10:
              if (field.Type == TType.Bool) {
                AimingThrow = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 11:
              if (field.Type == TType.Bool) {
                MovementInputSuppressed = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 12:
              if (field.Type == TType.Struct) {
                LastMoveInputDirection = new Point();
                LastMoveInputDirection.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 13:
              if (field.Type == TType.Double) {
                ImpactStartTime = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 14:
              if (field.Type == TType.Double) {
                ImpactTimer = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 15:
              if (field.Type == TType.Struct) {
                ImpactVelocity = new Point();
                ImpactVelocity.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 16:
              if (field.Type == TType.Double) {
                LeftOverTime = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ChefSpecificData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.highlightedForPickup) {
          field.Name = "highlightedForPickup";
          field.Type = TType.I32;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(HighlightedForPickup);
          oprot.WriteFieldEnd();
        }
        if (__isset.highlightedForUse) {
          field.Name = "highlightedForUse";
          field.Type = TType.I32;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(HighlightedForUse);
          oprot.WriteFieldEnd();
        }
        if (__isset.highlightedForPlacement) {
          field.Name = "highlightedForPlacement";
          field.Type = TType.I32;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(HighlightedForPlacement);
          oprot.WriteFieldEnd();
        }
        if (__isset.dashTimer) {
          field.Name = "dashTimer";
          field.Type = TType.Double;
          field.ID = 7;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(DashTimer);
          oprot.WriteFieldEnd();
        }
        if (__isset.interactingEntity) {
          field.Name = "interactingEntity";
          field.Type = TType.I32;
          field.ID = 8;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(InteractingEntity);
          oprot.WriteFieldEnd();
        }
        if (LastVelocity != null && __isset.lastVelocity) {
          field.Name = "lastVelocity";
          field.Type = TType.Struct;
          field.ID = 9;
          oprot.WriteFieldBegin(field);
          LastVelocity.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.aimingThrow) {
          field.Name = "aimingThrow";
          field.Type = TType.Bool;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(AimingThrow);
          oprot.WriteFieldEnd();
        }
        if (__isset.movementInputSuppressed) {
          field.Name = "movementInputSuppressed";
          field.Type = TType.Bool;
          field.ID = 11;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(MovementInputSuppressed);
          oprot.WriteFieldEnd();
        }
        if (LastMoveInputDirection != null && __isset.lastMoveInputDirection) {
          field.Name = "lastMoveInputDirection";
          field.Type = TType.Struct;
          field.ID = 12;
          oprot.WriteFieldBegin(field);
          LastMoveInputDirection.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.impactStartTime) {
          field.Name = "impactStartTime";
          field.Type = TType.Double;
          field.ID = 13;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(ImpactStartTime);
          oprot.WriteFieldEnd();
        }
        if (__isset.impactTimer) {
          field.Name = "impactTimer";
          field.Type = TType.Double;
          field.ID = 14;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(ImpactTimer);
          oprot.WriteFieldEnd();
        }
        if (ImpactVelocity != null && __isset.impactVelocity) {
          field.Name = "impactVelocity";
          field.Type = TType.Struct;
          field.ID = 15;
          oprot.WriteFieldBegin(field);
          ImpactVelocity.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.leftOverTime) {
          field.Name = "leftOverTime";
          field.Type = TType.Double;
          field.ID = 16;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(LeftOverTime);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ChefSpecificData(");
      bool __first = true;
      if (__isset.highlightedForPickup) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("HighlightedForPickup: ");
        __sb.Append(HighlightedForPickup);
      }
      if (__isset.highlightedForUse) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("HighlightedForUse: ");
        __sb.Append(HighlightedForUse);
      }
      if (__isset.highlightedForPlacement) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("HighlightedForPlacement: ");
        __sb.Append(HighlightedForPlacement);
      }
      if (__isset.dashTimer) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DashTimer: ");
        __sb.Append(DashTimer);
      }
      if (__isset.interactingEntity) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("InteractingEntity: ");
        __sb.Append(InteractingEntity);
      }
      if (LastVelocity != null && __isset.lastVelocity) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LastVelocity: ");
        __sb.Append(LastVelocity== null ? "<null>" : LastVelocity.ToString());
      }
      if (__isset.aimingThrow) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AimingThrow: ");
        __sb.Append(AimingThrow);
      }
      if (__isset.movementInputSuppressed) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("MovementInputSuppressed: ");
        __sb.Append(MovementInputSuppressed);
      }
      if (LastMoveInputDirection != null && __isset.lastMoveInputDirection) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LastMoveInputDirection: ");
        __sb.Append(LastMoveInputDirection== null ? "<null>" : LastMoveInputDirection.ToString());
      }
      if (__isset.impactStartTime) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ImpactStartTime: ");
        __sb.Append(ImpactStartTime);
      }
      if (__isset.impactTimer) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ImpactTimer: ");
        __sb.Append(ImpactTimer);
      }
      if (ImpactVelocity != null && __isset.impactVelocity) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ImpactVelocity: ");
        __sb.Append(ImpactVelocity== null ? "<null>" : ImpactVelocity.ToString());
      }
      if (__isset.leftOverTime) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LeftOverTime: ");
        __sb.Append(LeftOverTime);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
