/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ChefCarryWarpData : TBase
  {
    private EntityIdOrRef _carriedItem;

    public EntityIdOrRef CarriedItem
    {
      get
      {
        return _carriedItem;
      }
      set
      {
        __isset.carriedItem = true;
        this._carriedItem = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool carriedItem;
    }

    public ChefCarryWarpData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                CarriedItem = new EntityIdOrRef();
                CarriedItem.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ChefCarryWarpData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (CarriedItem != null && __isset.carriedItem) {
          field.Name = "carriedItem";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          CarriedItem.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ChefCarryWarpData(");
      bool __first = true;
      if (CarriedItem != null && __isset.carriedItem) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("CarriedItem: ");
        __sb.Append(CarriedItem== null ? "<null>" : CarriedItem.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
