/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ColliderRef : TBase
  {
    private EntityIdOrRef _entity;
    private int _colliderIndex;

    public EntityIdOrRef Entity
    {
      get
      {
        return _entity;
      }
      set
      {
        __isset.entity = true;
        this._entity = value;
      }
    }

    public int ColliderIndex
    {
      get
      {
        return _colliderIndex;
      }
      set
      {
        __isset.colliderIndex = true;
        this._colliderIndex = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool entity;
      public bool colliderIndex;
    }

    public ColliderRef() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Entity = new EntityIdOrRef();
                Entity.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                ColliderIndex = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ColliderRef");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Entity != null && __isset.entity) {
          field.Name = "entity";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Entity.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.colliderIndex) {
          field.Name = "colliderIndex";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ColliderIndex);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ColliderRef(");
      bool __first = true;
      if (Entity != null && __isset.entity) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Entity: ");
        __sb.Append(Entity== null ? "<null>" : Entity.ToString());
      }
      if (__isset.colliderIndex) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ColliderIndex: ");
        __sb.Append(ColliderIndex);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
