/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CookingStationWarpData : TBase
  {
    private bool _isTurnedOn;
    private bool _isCooking;

    public bool IsTurnedOn
    {
      get
      {
        return _isTurnedOn;
      }
      set
      {
        __isset.isTurnedOn = true;
        this._isTurnedOn = value;
      }
    }

    public bool IsCooking
    {
      get
      {
        return _isCooking;
      }
      set
      {
        __isset.isCooking = true;
        this._isCooking = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool isTurnedOn;
      public bool isCooking;
    }

    public CookingStationWarpData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool) {
                IsTurnedOn = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Bool) {
                IsCooking = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("CookingStationWarpData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.isTurnedOn) {
          field.Name = "isTurnedOn";
          field.Type = TType.Bool;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(IsTurnedOn);
          oprot.WriteFieldEnd();
        }
        if (__isset.isCooking) {
          field.Name = "isCooking";
          field.Type = TType.Bool;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(IsCooking);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("CookingStationWarpData(");
      bool __first = true;
      if (__isset.isTurnedOn) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IsTurnedOn: ");
        __sb.Append(IsTurnedOn);
      }
      if (__isset.isCooking) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IsCooking: ");
        __sb.Append(IsCooking);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
