/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class EntityRegistryData : TBase
  {
    private int _entityId;
    private string _name;
    private Point _pos;
    private List<string> _components;
    private List<int> _syncEntityTypes;
    private List<string> _spawnNames;

    public int EntityId
    {
      get
      {
        return _entityId;
      }
      set
      {
        __isset.entityId = true;
        this._entityId = value;
      }
    }

    public string Name
    {
      get
      {
        return _name;
      }
      set
      {
        __isset.name = true;
        this._name = value;
      }
    }

    public Point Pos
    {
      get
      {
        return _pos;
      }
      set
      {
        __isset.pos = true;
        this._pos = value;
      }
    }

    public List<string> Components
    {
      get
      {
        return _components;
      }
      set
      {
        __isset.components = true;
        this._components = value;
      }
    }

    public List<int> SyncEntityTypes
    {
      get
      {
        return _syncEntityTypes;
      }
      set
      {
        __isset.syncEntityTypes = true;
        this._syncEntityTypes = value;
      }
    }

    public List<string> SpawnNames
    {
      get
      {
        return _spawnNames;
      }
      set
      {
        __isset.spawnNames = true;
        this._spawnNames = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool entityId;
      public bool name;
      public bool pos;
      public bool components;
      public bool syncEntityTypes;
      public bool spawnNames;
    }

    public EntityRegistryData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                EntityId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Name = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Struct) {
                Pos = new Point();
                Pos.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.List) {
                {
                  Components = new List<string>();
                  TList _list4 = iprot.ReadListBegin();
                  for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
                  {
                    string _elem6;
                    _elem6 = iprot.ReadString();
                    Components.Add(_elem6);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.List) {
                {
                  SyncEntityTypes = new List<int>();
                  TList _list7 = iprot.ReadListBegin();
                  for( int _i8 = 0; _i8 < _list7.Count; ++_i8)
                  {
                    int _elem9;
                    _elem9 = iprot.ReadI32();
                    SyncEntityTypes.Add(_elem9);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.List) {
                {
                  SpawnNames = new List<string>();
                  TList _list10 = iprot.ReadListBegin();
                  for( int _i11 = 0; _i11 < _list10.Count; ++_i11)
                  {
                    string _elem12;
                    _elem12 = iprot.ReadString();
                    SpawnNames.Add(_elem12);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("EntityRegistryData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.entityId) {
          field.Name = "entityId";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(EntityId);
          oprot.WriteFieldEnd();
        }
        if (Name != null && __isset.name) {
          field.Name = "name";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Name);
          oprot.WriteFieldEnd();
        }
        if (Pos != null && __isset.pos) {
          field.Name = "pos";
          field.Type = TType.Struct;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          Pos.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Components != null && __isset.components) {
          field.Name = "components";
          field.Type = TType.List;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.String, Components.Count));
            foreach (string _iter13 in Components)
            {
              oprot.WriteString(_iter13);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (SyncEntityTypes != null && __isset.syncEntityTypes) {
          field.Name = "syncEntityTypes";
          field.Type = TType.List;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.I32, SyncEntityTypes.Count));
            foreach (int _iter14 in SyncEntityTypes)
            {
              oprot.WriteI32(_iter14);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (SpawnNames != null && __isset.spawnNames) {
          field.Name = "spawnNames";
          field.Type = TType.List;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.String, SpawnNames.Count));
            foreach (string _iter15 in SpawnNames)
            {
              oprot.WriteString(_iter15);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("EntityRegistryData(");
      bool __first = true;
      if (__isset.entityId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EntityId: ");
        __sb.Append(EntityId);
      }
      if (Name != null && __isset.name) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Name: ");
        __sb.Append(Name);
      }
      if (Pos != null && __isset.pos) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Pos: ");
        __sb.Append(Pos== null ? "<null>" : Pos.ToString());
      }
      if (Components != null && __isset.components) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Components: ");
        __sb.Append(Components);
      }
      if (SyncEntityTypes != null && __isset.syncEntityTypes) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("SyncEntityTypes: ");
        __sb.Append(SyncEntityTypes);
      }
      if (SpawnNames != null && __isset.spawnNames) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("SpawnNames: ");
        __sb.Append(SpawnNames);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
