/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class EntityWarpSpec : TBase
  {
    private int _entityId;
    private List<int> _spawningPath;
    private EntityPathReference _entityPathReference;
    private Point _position;
    private Quaternion _rotation;
    private Point _velocity;
    private Point _angularVelocity;
    private PlateStationWarpData _plateStation;
    private ChefSpecificData _chef;
    private IngredientContainerWarpData _ingredientContainer;
    private CannonWarpData _cannon;
    private WorkstationWarpData _workstation;
    private WorkableItemWarpData _workableItem;
    private ThrowableItemWarpData _throwableItem;
    private TerminalWarpData _terminal;
    private PilotRotationWarpData _pilotRotation;
    private MixingHandlerWarpData _mixingHandler;
    private CookingHandlerWarpData _cookingHandler;
    private ChefCarryWarpData _chefCarry;
    private AttachStationWarpData _attachStation;
    private PickupItemSwitcherWarpData _pickupItemSwitcher;
    private TriggerColourCycleWarpData _triggerColourCycle;
    private PlateReturnControllerWarpData _plateReturnController;
    private StackWarpData _stack;
    private WashingStationWarpData _washingStation;
    private KitchenControllerWarpData _kitchenController;
    private CookingStationWarpData _cookingStation;
    private PlateReturnStationWarpData _plateReturnStation;

    public int EntityId
    {
      get
      {
        return _entityId;
      }
      set
      {
        __isset.entityId = true;
        this._entityId = value;
      }
    }

    public List<int> SpawningPath
    {
      get
      {
        return _spawningPath;
      }
      set
      {
        __isset.spawningPath = true;
        this._spawningPath = value;
      }
    }

    public EntityPathReference EntityPathReference
    {
      get
      {
        return _entityPathReference;
      }
      set
      {
        __isset.entityPathReference = true;
        this._entityPathReference = value;
      }
    }

    public Point Position
    {
      get
      {
        return _position;
      }
      set
      {
        __isset.position = true;
        this._position = value;
      }
    }

    public Quaternion Rotation
    {
      get
      {
        return _rotation;
      }
      set
      {
        __isset.rotation = true;
        this._rotation = value;
      }
    }

    public Point Velocity
    {
      get
      {
        return _velocity;
      }
      set
      {
        __isset.velocity = true;
        this._velocity = value;
      }
    }

    public Point AngularVelocity
    {
      get
      {
        return _angularVelocity;
      }
      set
      {
        __isset.angularVelocity = true;
        this._angularVelocity = value;
      }
    }

    public PlateStationWarpData PlateStation
    {
      get
      {
        return _plateStation;
      }
      set
      {
        __isset.plateStation = true;
        this._plateStation = value;
      }
    }

    public ChefSpecificData Chef
    {
      get
      {
        return _chef;
      }
      set
      {
        __isset.chef = true;
        this._chef = value;
      }
    }

    public IngredientContainerWarpData IngredientContainer
    {
      get
      {
        return _ingredientContainer;
      }
      set
      {
        __isset.ingredientContainer = true;
        this._ingredientContainer = value;
      }
    }

    public CannonWarpData Cannon
    {
      get
      {
        return _cannon;
      }
      set
      {
        __isset.cannon = true;
        this._cannon = value;
      }
    }

    public WorkstationWarpData Workstation
    {
      get
      {
        return _workstation;
      }
      set
      {
        __isset.workstation = true;
        this._workstation = value;
      }
    }

    public WorkableItemWarpData WorkableItem
    {
      get
      {
        return _workableItem;
      }
      set
      {
        __isset.workableItem = true;
        this._workableItem = value;
      }
    }

    public ThrowableItemWarpData ThrowableItem
    {
      get
      {
        return _throwableItem;
      }
      set
      {
        __isset.throwableItem = true;
        this._throwableItem = value;
      }
    }

    public TerminalWarpData Terminal
    {
      get
      {
        return _terminal;
      }
      set
      {
        __isset.terminal = true;
        this._terminal = value;
      }
    }

    public PilotRotationWarpData PilotRotation
    {
      get
      {
        return _pilotRotation;
      }
      set
      {
        __isset.pilotRotation = true;
        this._pilotRotation = value;
      }
    }

    public MixingHandlerWarpData MixingHandler
    {
      get
      {
        return _mixingHandler;
      }
      set
      {
        __isset.mixingHandler = true;
        this._mixingHandler = value;
      }
    }

    public CookingHandlerWarpData CookingHandler
    {
      get
      {
        return _cookingHandler;
      }
      set
      {
        __isset.cookingHandler = true;
        this._cookingHandler = value;
      }
    }

    public ChefCarryWarpData ChefCarry
    {
      get
      {
        return _chefCarry;
      }
      set
      {
        __isset.chefCarry = true;
        this._chefCarry = value;
      }
    }

    public AttachStationWarpData AttachStation
    {
      get
      {
        return _attachStation;
      }
      set
      {
        __isset.attachStation = true;
        this._attachStation = value;
      }
    }

    public PickupItemSwitcherWarpData PickupItemSwitcher
    {
      get
      {
        return _pickupItemSwitcher;
      }
      set
      {
        __isset.pickupItemSwitcher = true;
        this._pickupItemSwitcher = value;
      }
    }

    public TriggerColourCycleWarpData TriggerColourCycle
    {
      get
      {
        return _triggerColourCycle;
      }
      set
      {
        __isset.triggerColourCycle = true;
        this._triggerColourCycle = value;
      }
    }

    public PlateReturnControllerWarpData PlateReturnController
    {
      get
      {
        return _plateReturnController;
      }
      set
      {
        __isset.plateReturnController = true;
        this._plateReturnController = value;
      }
    }

    public StackWarpData Stack
    {
      get
      {
        return _stack;
      }
      set
      {
        __isset.stack = true;
        this._stack = value;
      }
    }

    public WashingStationWarpData WashingStation
    {
      get
      {
        return _washingStation;
      }
      set
      {
        __isset.washingStation = true;
        this._washingStation = value;
      }
    }

    public KitchenControllerWarpData KitchenController
    {
      get
      {
        return _kitchenController;
      }
      set
      {
        __isset.kitchenController = true;
        this._kitchenController = value;
      }
    }

    public CookingStationWarpData CookingStation
    {
      get
      {
        return _cookingStation;
      }
      set
      {
        __isset.cookingStation = true;
        this._cookingStation = value;
      }
    }

    public PlateReturnStationWarpData PlateReturnStation
    {
      get
      {
        return _plateReturnStation;
      }
      set
      {
        __isset.plateReturnStation = true;
        this._plateReturnStation = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool entityId;
      public bool spawningPath;
      public bool entityPathReference;
      public bool position;
      public bool rotation;
      public bool velocity;
      public bool angularVelocity;
      public bool plateStation;
      public bool chef;
      public bool ingredientContainer;
      public bool cannon;
      public bool workstation;
      public bool workableItem;
      public bool throwableItem;
      public bool terminal;
      public bool pilotRotation;
      public bool mixingHandler;
      public bool cookingHandler;
      public bool chefCarry;
      public bool attachStation;
      public bool pickupItemSwitcher;
      public bool triggerColourCycle;
      public bool plateReturnController;
      public bool stack;
      public bool washingStation;
      public bool kitchenController;
      public bool cookingStation;
      public bool plateReturnStation;
    }

    public EntityWarpSpec() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                EntityId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  SpawningPath = new List<int>();
                  TList _list58 = iprot.ReadListBegin();
                  for( int _i59 = 0; _i59 < _list58.Count; ++_i59)
                  {
                    int _elem60;
                    _elem60 = iprot.ReadI32();
                    SpawningPath.Add(_elem60);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Struct) {
                EntityPathReference = new EntityPathReference();
                EntityPathReference.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.Struct) {
                Position = new Point();
                Position.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.Struct) {
                Rotation = new Quaternion();
                Rotation.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.Struct) {
                Velocity = new Point();
                Velocity.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 11:
              if (field.Type == TType.Struct) {
                AngularVelocity = new Point();
                AngularVelocity.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 8:
              if (field.Type == TType.Struct) {
                PlateStation = new PlateStationWarpData();
                PlateStation.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 9:
              if (field.Type == TType.Struct) {
                Chef = new ChefSpecificData();
                Chef.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 10:
              if (field.Type == TType.Struct) {
                IngredientContainer = new IngredientContainerWarpData();
                IngredientContainer.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 12:
              if (field.Type == TType.Struct) {
                Cannon = new CannonWarpData();
                Cannon.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 13:
              if (field.Type == TType.Struct) {
                Workstation = new WorkstationWarpData();
                Workstation.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 14:
              if (field.Type == TType.Struct) {
                WorkableItem = new WorkableItemWarpData();
                WorkableItem.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 15:
              if (field.Type == TType.Struct) {
                ThrowableItem = new ThrowableItemWarpData();
                ThrowableItem.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 16:
              if (field.Type == TType.Struct) {
                Terminal = new TerminalWarpData();
                Terminal.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 17:
              if (field.Type == TType.Struct) {
                PilotRotation = new PilotRotationWarpData();
                PilotRotation.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 18:
              if (field.Type == TType.Struct) {
                MixingHandler = new MixingHandlerWarpData();
                MixingHandler.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 19:
              if (field.Type == TType.Struct) {
                CookingHandler = new CookingHandlerWarpData();
                CookingHandler.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 20:
              if (field.Type == TType.Struct) {
                ChefCarry = new ChefCarryWarpData();
                ChefCarry.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 21:
              if (field.Type == TType.Struct) {
                AttachStation = new AttachStationWarpData();
                AttachStation.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 22:
              if (field.Type == TType.Struct) {
                PickupItemSwitcher = new PickupItemSwitcherWarpData();
                PickupItemSwitcher.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 23:
              if (field.Type == TType.Struct) {
                TriggerColourCycle = new TriggerColourCycleWarpData();
                TriggerColourCycle.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 24:
              if (field.Type == TType.Struct) {
                PlateReturnController = new PlateReturnControllerWarpData();
                PlateReturnController.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 25:
              if (field.Type == TType.Struct) {
                Stack = new StackWarpData();
                Stack.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 26:
              if (field.Type == TType.Struct) {
                WashingStation = new WashingStationWarpData();
                WashingStation.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 27:
              if (field.Type == TType.Struct) {
                KitchenController = new KitchenControllerWarpData();
                KitchenController.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 28:
              if (field.Type == TType.Struct) {
                CookingStation = new CookingStationWarpData();
                CookingStation.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 29:
              if (field.Type == TType.Struct) {
                PlateReturnStation = new PlateReturnStationWarpData();
                PlateReturnStation.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("EntityWarpSpec");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.entityId) {
          field.Name = "entityId";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(EntityId);
          oprot.WriteFieldEnd();
        }
        if (SpawningPath != null && __isset.spawningPath) {
          field.Name = "spawningPath";
          field.Type = TType.List;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.I32, SpawningPath.Count));
            foreach (int _iter61 in SpawningPath)
            {
              oprot.WriteI32(_iter61);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (EntityPathReference != null && __isset.entityPathReference) {
          field.Name = "entityPathReference";
          field.Type = TType.Struct;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          EntityPathReference.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Position != null && __isset.position) {
          field.Name = "position";
          field.Type = TType.Struct;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          Position.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Rotation != null && __isset.rotation) {
          field.Name = "rotation";
          field.Type = TType.Struct;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          Rotation.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Velocity != null && __isset.velocity) {
          field.Name = "velocity";
          field.Type = TType.Struct;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          Velocity.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (PlateStation != null && __isset.plateStation) {
          field.Name = "plateStation";
          field.Type = TType.Struct;
          field.ID = 8;
          oprot.WriteFieldBegin(field);
          PlateStation.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Chef != null && __isset.chef) {
          field.Name = "chef";
          field.Type = TType.Struct;
          field.ID = 9;
          oprot.WriteFieldBegin(field);
          Chef.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (IngredientContainer != null && __isset.ingredientContainer) {
          field.Name = "ingredientContainer";
          field.Type = TType.Struct;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          IngredientContainer.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (AngularVelocity != null && __isset.angularVelocity) {
          field.Name = "angularVelocity";
          field.Type = TType.Struct;
          field.ID = 11;
          oprot.WriteFieldBegin(field);
          AngularVelocity.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Cannon != null && __isset.cannon) {
          field.Name = "cannon";
          field.Type = TType.Struct;
          field.ID = 12;
          oprot.WriteFieldBegin(field);
          Cannon.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Workstation != null && __isset.workstation) {
          field.Name = "workstation";
          field.Type = TType.Struct;
          field.ID = 13;
          oprot.WriteFieldBegin(field);
          Workstation.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (WorkableItem != null && __isset.workableItem) {
          field.Name = "workableItem";
          field.Type = TType.Struct;
          field.ID = 14;
          oprot.WriteFieldBegin(field);
          WorkableItem.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (ThrowableItem != null && __isset.throwableItem) {
          field.Name = "throwableItem";
          field.Type = TType.Struct;
          field.ID = 15;
          oprot.WriteFieldBegin(field);
          ThrowableItem.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Terminal != null && __isset.terminal) {
          field.Name = "terminal";
          field.Type = TType.Struct;
          field.ID = 16;
          oprot.WriteFieldBegin(field);
          Terminal.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (PilotRotation != null && __isset.pilotRotation) {
          field.Name = "pilotRotation";
          field.Type = TType.Struct;
          field.ID = 17;
          oprot.WriteFieldBegin(field);
          PilotRotation.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (MixingHandler != null && __isset.mixingHandler) {
          field.Name = "mixingHandler";
          field.Type = TType.Struct;
          field.ID = 18;
          oprot.WriteFieldBegin(field);
          MixingHandler.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (CookingHandler != null && __isset.cookingHandler) {
          field.Name = "cookingHandler";
          field.Type = TType.Struct;
          field.ID = 19;
          oprot.WriteFieldBegin(field);
          CookingHandler.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (ChefCarry != null && __isset.chefCarry) {
          field.Name = "chefCarry";
          field.Type = TType.Struct;
          field.ID = 20;
          oprot.WriteFieldBegin(field);
          ChefCarry.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (AttachStation != null && __isset.attachStation) {
          field.Name = "attachStation";
          field.Type = TType.Struct;
          field.ID = 21;
          oprot.WriteFieldBegin(field);
          AttachStation.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (PickupItemSwitcher != null && __isset.pickupItemSwitcher) {
          field.Name = "pickupItemSwitcher";
          field.Type = TType.Struct;
          field.ID = 22;
          oprot.WriteFieldBegin(field);
          PickupItemSwitcher.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (TriggerColourCycle != null && __isset.triggerColourCycle) {
          field.Name = "triggerColourCycle";
          field.Type = TType.Struct;
          field.ID = 23;
          oprot.WriteFieldBegin(field);
          TriggerColourCycle.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (PlateReturnController != null && __isset.plateReturnController) {
          field.Name = "plateReturnController";
          field.Type = TType.Struct;
          field.ID = 24;
          oprot.WriteFieldBegin(field);
          PlateReturnController.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Stack != null && __isset.stack) {
          field.Name = "stack";
          field.Type = TType.Struct;
          field.ID = 25;
          oprot.WriteFieldBegin(field);
          Stack.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (WashingStation != null && __isset.washingStation) {
          field.Name = "washingStation";
          field.Type = TType.Struct;
          field.ID = 26;
          oprot.WriteFieldBegin(field);
          WashingStation.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (KitchenController != null && __isset.kitchenController) {
          field.Name = "kitchenController";
          field.Type = TType.Struct;
          field.ID = 27;
          oprot.WriteFieldBegin(field);
          KitchenController.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (CookingStation != null && __isset.cookingStation) {
          field.Name = "cookingStation";
          field.Type = TType.Struct;
          field.ID = 28;
          oprot.WriteFieldBegin(field);
          CookingStation.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (PlateReturnStation != null && __isset.plateReturnStation) {
          field.Name = "plateReturnStation";
          field.Type = TType.Struct;
          field.ID = 29;
          oprot.WriteFieldBegin(field);
          PlateReturnStation.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("EntityWarpSpec(");
      bool __first = true;
      if (__isset.entityId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EntityId: ");
        __sb.Append(EntityId);
      }
      if (SpawningPath != null && __isset.spawningPath) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("SpawningPath: ");
        __sb.Append(SpawningPath);
      }
      if (EntityPathReference != null && __isset.entityPathReference) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EntityPathReference: ");
        __sb.Append(EntityPathReference== null ? "<null>" : EntityPathReference.ToString());
      }
      if (Position != null && __isset.position) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Position: ");
        __sb.Append(Position== null ? "<null>" : Position.ToString());
      }
      if (Rotation != null && __isset.rotation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Rotation: ");
        __sb.Append(Rotation== null ? "<null>" : Rotation.ToString());
      }
      if (Velocity != null && __isset.velocity) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Velocity: ");
        __sb.Append(Velocity== null ? "<null>" : Velocity.ToString());
      }
      if (AngularVelocity != null && __isset.angularVelocity) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AngularVelocity: ");
        __sb.Append(AngularVelocity== null ? "<null>" : AngularVelocity.ToString());
      }
      if (PlateStation != null && __isset.plateStation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PlateStation: ");
        __sb.Append(PlateStation== null ? "<null>" : PlateStation.ToString());
      }
      if (Chef != null && __isset.chef) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Chef: ");
        __sb.Append(Chef== null ? "<null>" : Chef.ToString());
      }
      if (IngredientContainer != null && __isset.ingredientContainer) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IngredientContainer: ");
        __sb.Append(IngredientContainer== null ? "<null>" : IngredientContainer.ToString());
      }
      if (Cannon != null && __isset.cannon) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Cannon: ");
        __sb.Append(Cannon== null ? "<null>" : Cannon.ToString());
      }
      if (Workstation != null && __isset.workstation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Workstation: ");
        __sb.Append(Workstation== null ? "<null>" : Workstation.ToString());
      }
      if (WorkableItem != null && __isset.workableItem) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("WorkableItem: ");
        __sb.Append(WorkableItem== null ? "<null>" : WorkableItem.ToString());
      }
      if (ThrowableItem != null && __isset.throwableItem) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ThrowableItem: ");
        __sb.Append(ThrowableItem== null ? "<null>" : ThrowableItem.ToString());
      }
      if (Terminal != null && __isset.terminal) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Terminal: ");
        __sb.Append(Terminal== null ? "<null>" : Terminal.ToString());
      }
      if (PilotRotation != null && __isset.pilotRotation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PilotRotation: ");
        __sb.Append(PilotRotation== null ? "<null>" : PilotRotation.ToString());
      }
      if (MixingHandler != null && __isset.mixingHandler) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("MixingHandler: ");
        __sb.Append(MixingHandler== null ? "<null>" : MixingHandler.ToString());
      }
      if (CookingHandler != null && __isset.cookingHandler) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("CookingHandler: ");
        __sb.Append(CookingHandler== null ? "<null>" : CookingHandler.ToString());
      }
      if (ChefCarry != null && __isset.chefCarry) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ChefCarry: ");
        __sb.Append(ChefCarry== null ? "<null>" : ChefCarry.ToString());
      }
      if (AttachStation != null && __isset.attachStation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AttachStation: ");
        __sb.Append(AttachStation== null ? "<null>" : AttachStation.ToString());
      }
      if (PickupItemSwitcher != null && __isset.pickupItemSwitcher) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PickupItemSwitcher: ");
        __sb.Append(PickupItemSwitcher== null ? "<null>" : PickupItemSwitcher.ToString());
      }
      if (TriggerColourCycle != null && __isset.triggerColourCycle) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TriggerColourCycle: ");
        __sb.Append(TriggerColourCycle== null ? "<null>" : TriggerColourCycle.ToString());
      }
      if (PlateReturnController != null && __isset.plateReturnController) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PlateReturnController: ");
        __sb.Append(PlateReturnController== null ? "<null>" : PlateReturnController.ToString());
      }
      if (Stack != null && __isset.stack) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Stack: ");
        __sb.Append(Stack== null ? "<null>" : Stack.ToString());
      }
      if (WashingStation != null && __isset.washingStation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("WashingStation: ");
        __sb.Append(WashingStation== null ? "<null>" : WashingStation.ToString());
      }
      if (KitchenController != null && __isset.kitchenController) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("KitchenController: ");
        __sb.Append(KitchenController== null ? "<null>" : KitchenController.ToString());
      }
      if (CookingStation != null && __isset.cookingStation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("CookingStation: ");
        __sb.Append(CookingStation== null ? "<null>" : CookingStation.ToString());
      }
      if (PlateReturnStation != null && __isset.plateReturnStation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PlateReturnStation: ");
        __sb.Append(PlateReturnStation== null ? "<null>" : PlateReturnStation.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
