/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class EntityIdOrRef : TBase
  {
    private int _entityId;
    private EntityPathReference _entityPathReference;

    public int EntityId
    {
      get
      {
        return _entityId;
      }
      set
      {
        __isset.entityId = true;
        this._entityId = value;
      }
    }

    public EntityPathReference EntityPathReference
    {
      get
      {
        return _entityPathReference;
      }
      set
      {
        __isset.entityPathReference = true;
        this._entityPathReference = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool entityId;
      public bool entityPathReference;
    }

    public EntityIdOrRef() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                EntityId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                EntityPathReference = new EntityPathReference();
                EntityPathReference.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("EntityIdOrRef");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.entityId) {
          field.Name = "entityId";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(EntityId);
          oprot.WriteFieldEnd();
        }
        if (EntityPathReference != null && __isset.entityPathReference) {
          field.Name = "entityPathReference";
          field.Type = TType.Struct;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          EntityPathReference.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("EntityIdOrRef(");
      bool __first = true;
      if (__isset.entityId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EntityId: ");
        __sb.Append(EntityId);
      }
      if (EntityPathReference != null && __isset.entityPathReference) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EntityPathReference: ");
        __sb.Append(EntityPathReference== null ? "<null>" : EntityPathReference.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
