/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class InputData : TBase
  {
    private Dictionary<int, OneInputData> _input;
    private int _resetOrderSeed;
    private double _gameSpeed;
    private WarpSpec _warp;
    private bool _requestPause;
    private bool _requestResume;
    private int _nextFrame;
    private bool _preventInvalidState;

    public Dictionary<int, OneInputData> Input
    {
      get
      {
        return _input;
      }
      set
      {
        __isset.input = true;
        this._input = value;
      }
    }

    public int ResetOrderSeed
    {
      get
      {
        return _resetOrderSeed;
      }
      set
      {
        __isset.resetOrderSeed = true;
        this._resetOrderSeed = value;
      }
    }

    public double GameSpeed
    {
      get
      {
        return _gameSpeed;
      }
      set
      {
        __isset.gameSpeed = true;
        this._gameSpeed = value;
      }
    }

    public WarpSpec Warp
    {
      get
      {
        return _warp;
      }
      set
      {
        __isset.warp = true;
        this._warp = value;
      }
    }

    public bool RequestPause
    {
      get
      {
        return _requestPause;
      }
      set
      {
        __isset.requestPause = true;
        this._requestPause = value;
      }
    }

    public bool RequestResume
    {
      get
      {
        return _requestResume;
      }
      set
      {
        __isset.requestResume = true;
        this._requestResume = value;
      }
    }

    public int NextFrame
    {
      get
      {
        return _nextFrame;
      }
      set
      {
        __isset.nextFrame = true;
        this._nextFrame = value;
      }
    }

    public bool PreventInvalidState
    {
      get
      {
        return _preventInvalidState;
      }
      set
      {
        __isset.preventInvalidState = true;
        this._preventInvalidState = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool input;
      public bool resetOrderSeed;
      public bool gameSpeed;
      public bool warp;
      public bool requestPause;
      public bool requestResume;
      public bool nextFrame;
      public bool preventInvalidState;
    }

    public InputData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Map) {
                {
                  Input = new Dictionary<int, OneInputData>();
                  TMap _map70 = iprot.ReadMapBegin();
                  for( int _i71 = 0; _i71 < _map70.Count; ++_i71)
                  {
                    int _key72;
                    OneInputData _val73;
                    _key72 = iprot.ReadI32();
                    _val73 = new OneInputData();
                    _val73.Read(iprot);
                    Input[_key72] = _val73;
                  }
                  iprot.ReadMapEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                ResetOrderSeed = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Double) {
                GameSpeed = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.Struct) {
                Warp = new WarpSpec();
                Warp.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.Bool) {
                RequestPause = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.Bool) {
                RequestResume = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 7:
              if (field.Type == TType.I32) {
                NextFrame = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 8:
              if (field.Type == TType.Bool) {
                PreventInvalidState = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("InputData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Input != null && __isset.input) {
          field.Name = "input";
          field.Type = TType.Map;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, Input.Count));
            foreach (int _iter74 in Input.Keys)
            {
              oprot.WriteI32(_iter74);
              Input[_iter74].Write(oprot);
            }
            oprot.WriteMapEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (__isset.resetOrderSeed) {
          field.Name = "resetOrderSeed";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ResetOrderSeed);
          oprot.WriteFieldEnd();
        }
        if (__isset.gameSpeed) {
          field.Name = "gameSpeed";
          field.Type = TType.Double;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(GameSpeed);
          oprot.WriteFieldEnd();
        }
        if (Warp != null && __isset.warp) {
          field.Name = "warp";
          field.Type = TType.Struct;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          Warp.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.requestPause) {
          field.Name = "requestPause";
          field.Type = TType.Bool;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(RequestPause);
          oprot.WriteFieldEnd();
        }
        if (__isset.requestResume) {
          field.Name = "requestResume";
          field.Type = TType.Bool;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(RequestResume);
          oprot.WriteFieldEnd();
        }
        if (__isset.nextFrame) {
          field.Name = "nextFrame";
          field.Type = TType.I32;
          field.ID = 7;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(NextFrame);
          oprot.WriteFieldEnd();
        }
        if (__isset.preventInvalidState) {
          field.Name = "preventInvalidState";
          field.Type = TType.Bool;
          field.ID = 8;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(PreventInvalidState);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("InputData(");
      bool __first = true;
      if (Input != null && __isset.input) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Input: ");
        __sb.Append(Input);
      }
      if (__isset.resetOrderSeed) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ResetOrderSeed: ");
        __sb.Append(ResetOrderSeed);
      }
      if (__isset.gameSpeed) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("GameSpeed: ");
        __sb.Append(GameSpeed);
      }
      if (Warp != null && __isset.warp) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Warp: ");
        __sb.Append(Warp== null ? "<null>" : Warp.ToString());
      }
      if (__isset.requestPause) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RequestPause: ");
        __sb.Append(RequestPause);
      }
      if (__isset.requestResume) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RequestResume: ");
        __sb.Append(RequestResume);
      }
      if (__isset.nextFrame) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NextFrame: ");
        __sb.Append(NextFrame);
      }
      if (__isset.preventInvalidState) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PreventInvalidState: ");
        __sb.Append(PreventInvalidState);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
