/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ItemData : TBase
  {
    private Point _pos;
    private Quaternion _rotation;
    private Point _velocity;
    private Point _angularVelocity;
    private EntityPathReference _entityPathReference;

    public Point Pos
    {
      get
      {
        return _pos;
      }
      set
      {
        __isset.pos = true;
        this._pos = value;
      }
    }

    public Quaternion Rotation
    {
      get
      {
        return _rotation;
      }
      set
      {
        __isset.rotation = true;
        this._rotation = value;
      }
    }

    public Point Velocity
    {
      get
      {
        return _velocity;
      }
      set
      {
        __isset.velocity = true;
        this._velocity = value;
      }
    }

    public Point AngularVelocity
    {
      get
      {
        return _angularVelocity;
      }
      set
      {
        __isset.angularVelocity = true;
        this._angularVelocity = value;
      }
    }

    public EntityPathReference EntityPathReference
    {
      get
      {
        return _entityPathReference;
      }
      set
      {
        __isset.entityPathReference = true;
        this._entityPathReference = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool pos;
      public bool rotation;
      public bool velocity;
      public bool angularVelocity;
      public bool entityPathReference;
    }

    public ItemData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Pos = new Point();
                Pos.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.Struct) {
                Rotation = new Quaternion();
                Rotation.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Struct) {
                Velocity = new Point();
                Velocity.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.Struct) {
                AngularVelocity = new Point();
                AngularVelocity.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.Struct) {
                EntityPathReference = new EntityPathReference();
                EntityPathReference.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ItemData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Pos != null && __isset.pos) {
          field.Name = "pos";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Pos.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Velocity != null && __isset.velocity) {
          field.Name = "velocity";
          field.Type = TType.Struct;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          Velocity.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Rotation != null && __isset.rotation) {
          field.Name = "rotation";
          field.Type = TType.Struct;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          Rotation.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (EntityPathReference != null && __isset.entityPathReference) {
          field.Name = "entityPathReference";
          field.Type = TType.Struct;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          EntityPathReference.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (AngularVelocity != null && __isset.angularVelocity) {
          field.Name = "angularVelocity";
          field.Type = TType.Struct;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          AngularVelocity.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ItemData(");
      bool __first = true;
      if (Pos != null && __isset.pos) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Pos: ");
        __sb.Append(Pos== null ? "<null>" : Pos.ToString());
      }
      if (Rotation != null && __isset.rotation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Rotation: ");
        __sb.Append(Rotation== null ? "<null>" : Rotation.ToString());
      }
      if (Velocity != null && __isset.velocity) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Velocity: ");
        __sb.Append(Velocity== null ? "<null>" : Velocity.ToString());
      }
      if (AngularVelocity != null && __isset.angularVelocity) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AngularVelocity: ");
        __sb.Append(AngularVelocity== null ? "<null>" : AngularVelocity.ToString());
      }
      if (EntityPathReference != null && __isset.entityPathReference) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EntityPathReference: ");
        __sb.Append(EntityPathReference== null ? "<null>" : EntityPathReference.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
