/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class KitchenControllerWarpData : TBase
  {
    private double _roundTime;
    private List<byte[]> _activeOrders;
    private int _nextOrderId;
    private int _lastComboIndex;
    private double _timeSinceLastOrder;
    private byte[] _teamScore;

    public double RoundTime
    {
      get
      {
        return _roundTime;
      }
      set
      {
        __isset.roundTime = true;
        this._roundTime = value;
      }
    }

    public List<byte[]> ActiveOrders
    {
      get
      {
        return _activeOrders;
      }
      set
      {
        __isset.activeOrders = true;
        this._activeOrders = value;
      }
    }

    public int NextOrderId
    {
      get
      {
        return _nextOrderId;
      }
      set
      {
        __isset.nextOrderId = true;
        this._nextOrderId = value;
      }
    }

    public int LastComboIndex
    {
      get
      {
        return _lastComboIndex;
      }
      set
      {
        __isset.lastComboIndex = true;
        this._lastComboIndex = value;
      }
    }

    public double TimeSinceLastOrder
    {
      get
      {
        return _timeSinceLastOrder;
      }
      set
      {
        __isset.timeSinceLastOrder = true;
        this._timeSinceLastOrder = value;
      }
    }

    public byte[] TeamScore
    {
      get
      {
        return _teamScore;
      }
      set
      {
        __isset.teamScore = true;
        this._teamScore = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool roundTime;
      public bool activeOrders;
      public bool nextOrderId;
      public bool lastComboIndex;
      public bool timeSinceLastOrder;
      public bool teamScore;
    }

    public KitchenControllerWarpData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Double) {
                RoundTime = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  ActiveOrders = new List<byte[]>();
                  TList _list54 = iprot.ReadListBegin();
                  for( int _i55 = 0; _i55 < _list54.Count; ++_i55)
                  {
                    byte[] _elem56;
                    _elem56 = iprot.ReadBinary();
                    ActiveOrders.Add(_elem56);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                NextOrderId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I32) {
                LastComboIndex = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.Double) {
                TimeSinceLastOrder = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.String) {
                TeamScore = iprot.ReadBinary();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("KitchenControllerWarpData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.roundTime) {
          field.Name = "roundTime";
          field.Type = TType.Double;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(RoundTime);
          oprot.WriteFieldEnd();
        }
        if (ActiveOrders != null && __isset.activeOrders) {
          field.Name = "activeOrders";
          field.Type = TType.List;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.String, ActiveOrders.Count));
            foreach (byte[] _iter57 in ActiveOrders)
            {
              oprot.WriteBinary(_iter57);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (__isset.nextOrderId) {
          field.Name = "nextOrderId";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(NextOrderId);
          oprot.WriteFieldEnd();
        }
        if (__isset.lastComboIndex) {
          field.Name = "lastComboIndex";
          field.Type = TType.I32;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(LastComboIndex);
          oprot.WriteFieldEnd();
        }
        if (__isset.timeSinceLastOrder) {
          field.Name = "timeSinceLastOrder";
          field.Type = TType.Double;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(TimeSinceLastOrder);
          oprot.WriteFieldEnd();
        }
        if (TeamScore != null && __isset.teamScore) {
          field.Name = "teamScore";
          field.Type = TType.String;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          oprot.WriteBinary(TeamScore);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("KitchenControllerWarpData(");
      bool __first = true;
      if (__isset.roundTime) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RoundTime: ");
        __sb.Append(RoundTime);
      }
      if (ActiveOrders != null && __isset.activeOrders) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ActiveOrders: ");
        __sb.Append(ActiveOrders);
      }
      if (__isset.nextOrderId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NextOrderId: ");
        __sb.Append(NextOrderId);
      }
      if (__isset.lastComboIndex) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LastComboIndex: ");
        __sb.Append(LastComboIndex);
      }
      if (__isset.timeSinceLastOrder) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TimeSinceLastOrder: ");
        __sb.Append(TimeSinceLastOrder);
      }
      if (TeamScore != null && __isset.teamScore) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TeamScore: ");
        __sb.Append(TeamScore);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
