/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class OneInputData : TBase
  {
    private PadDirection _pad;
    private ButtonInput _pickup;
    private ButtonInput _interact;
    private ButtonInput _dash;

    public PadDirection Pad
    {
      get
      {
        return _pad;
      }
      set
      {
        __isset.pad = true;
        this._pad = value;
      }
    }

    public ButtonInput Pickup
    {
      get
      {
        return _pickup;
      }
      set
      {
        __isset.pickup = true;
        this._pickup = value;
      }
    }

    public ButtonInput Interact
    {
      get
      {
        return _interact;
      }
      set
      {
        __isset.interact = true;
        this._interact = value;
      }
    }

    public ButtonInput Dash
    {
      get
      {
        return _dash;
      }
      set
      {
        __isset.dash = true;
        this._dash = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool pad;
      public bool pickup;
      public bool interact;
      public bool dash;
    }

    public OneInputData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Pad = new PadDirection();
                Pad.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 7:
              if (field.Type == TType.Struct) {
                Pickup = new ButtonInput();
                Pickup.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 8:
              if (field.Type == TType.Struct) {
                Interact = new ButtonInput();
                Interact.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 9:
              if (field.Type == TType.Struct) {
                Dash = new ButtonInput();
                Dash.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("OneInputData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Pad != null && __isset.pad) {
          field.Name = "pad";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Pad.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Pickup != null && __isset.pickup) {
          field.Name = "pickup";
          field.Type = TType.Struct;
          field.ID = 7;
          oprot.WriteFieldBegin(field);
          Pickup.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Interact != null && __isset.interact) {
          field.Name = "interact";
          field.Type = TType.Struct;
          field.ID = 8;
          oprot.WriteFieldBegin(field);
          Interact.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Dash != null && __isset.dash) {
          field.Name = "dash";
          field.Type = TType.Struct;
          field.ID = 9;
          oprot.WriteFieldBegin(field);
          Dash.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("OneInputData(");
      bool __first = true;
      if (Pad != null && __isset.pad) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Pad: ");
        __sb.Append(Pad== null ? "<null>" : Pad.ToString());
      }
      if (Pickup != null && __isset.pickup) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Pickup: ");
        __sb.Append(Pickup== null ? "<null>" : Pickup.ToString());
      }
      if (Interact != null && __isset.interact) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Interact: ");
        __sb.Append(Interact== null ? "<null>" : Interact.ToString());
      }
      if (Dash != null && __isset.dash) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Dash: ");
        __sb.Append(Dash== null ? "<null>" : Dash.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
