/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class OutputData : TBase
  {
    private Dictionary<int, ChefSpecificData> _chefs;
    private Dictionary<int, ItemData> _items;
    private List<ServerMessage> _serverMessages;
    private List<EntityRegistryData> _entityRegistry;
    private bool _lastFramePaused;
    private bool _nextFramePaused;
    private int _frameNumber;
    private string _invalidStateReason;
    private int _physicsFramesElapsed;
    private int _framesSinceLastNoPhysicsFrame;
    private double _roundTimeSeconds;
    private double _roundTimeRemainingSeconds;
    private int _episodeId;
    private int _episodeStep;
    private bool _inEpisode;
    private bool _episodeStart;
    private bool _episodeEnd;
    private string _episodeEndReason;
    private string _gameState;
    private string _levelName;
    private Dictionary<int, OneInputData> _observedInput;
    private bool _fullSnapshot;
    private List<EntityWarpSpec> _entityState;

    public Dictionary<int, ChefSpecificData> Chefs
    {
      get
      {
        return _chefs;
      }
      set
      {
        __isset.chefs = true;
        this._chefs = value;
      }
    }

    public Dictionary<int, ItemData> Items
    {
      get
      {
        return _items;
      }
      set
      {
        __isset.items = true;
        this._items = value;
      }
    }

    public List<ServerMessage> ServerMessages
    {
      get
      {
        return _serverMessages;
      }
      set
      {
        __isset.serverMessages = true;
        this._serverMessages = value;
      }
    }

    public List<EntityRegistryData> EntityRegistry
    {
      get
      {
        return _entityRegistry;
      }
      set
      {
        __isset.entityRegistry = true;
        this._entityRegistry = value;
      }
    }

    public bool LastFramePaused
    {
      get
      {
        return _lastFramePaused;
      }
      set
      {
        __isset.lastFramePaused = true;
        this._lastFramePaused = value;
      }
    }

    public bool NextFramePaused
    {
      get
      {
        return _nextFramePaused;
      }
      set
      {
        __isset.nextFramePaused = true;
        this._nextFramePaused = value;
      }
    }

    public int FrameNumber
    {
      get
      {
        return _frameNumber;
      }
      set
      {
        __isset.frameNumber = true;
        this._frameNumber = value;
      }
    }

    public string InvalidStateReason
    {
      get
      {
        return _invalidStateReason;
      }
      set
      {
        __isset.invalidStateReason = true;
        this._invalidStateReason = value;
      }
    }

    public int PhysicsFramesElapsed
    {
      get
      {
        return _physicsFramesElapsed;
      }
      set
      {
        __isset.physicsFramesElapsed = true;
        this._physicsFramesElapsed = value;
      }
    }

    public int FramesSinceLastNoPhysicsFrame
    {
      get
      {
        return _framesSinceLastNoPhysicsFrame;
      }
      set
      {
        __isset.framesSinceLastNoPhysicsFrame = true;
        this._framesSinceLastNoPhysicsFrame = value;
      }
    }

    public double RoundTimeSeconds
    {
      get
      {
        return _roundTimeSeconds;
      }
      set
      {
        __isset.roundTimeSeconds = true;
        this._roundTimeSeconds = value;
      }
    }

    public double RoundTimeRemainingSeconds
    {
      get
      {
        return _roundTimeRemainingSeconds;
      }
      set
      {
        __isset.roundTimeRemainingSeconds = true;
        this._roundTimeRemainingSeconds = value;
      }
    }

    public int EpisodeId
    {
      get
      {
        return _episodeId;
      }
      set
      {
        __isset.episodeId = true;
        this._episodeId = value;
      }
    }

    public int EpisodeStep
    {
      get
      {
        return _episodeStep;
      }
      set
      {
        __isset.episodeStep = true;
        this._episodeStep = value;
      }
    }

    public bool InEpisode
    {
      get
      {
        return _inEpisode;
      }
      set
      {
        __isset.inEpisode = true;
        this._inEpisode = value;
      }
    }

    public bool EpisodeStart
    {
      get
      {
        return _episodeStart;
      }
      set
      {
        __isset.episodeStart = true;
        this._episodeStart = value;
      }
    }

    public bool EpisodeEnd
    {
      get
      {
        return _episodeEnd;
      }
      set
      {
        __isset.episodeEnd = true;
        this._episodeEnd = value;
      }
    }

    public string EpisodeEndReason
    {
      get
      {
        return _episodeEndReason;
      }
      set
      {
        __isset.episodeEndReason = true;
        this._episodeEndReason = value;
      }
    }

    public string GameState
    {
      get
      {
        return _gameState;
      }
      set
      {
        __isset.gameState = true;
        this._gameState = value;
      }
    }

    public string LevelName
    {
      get
      {
        return _levelName;
      }
      set
      {
        __isset.levelName = true;
        this._levelName = value;
      }
    }

    public Dictionary<int, OneInputData> ObservedInput
    {
      get
      {
        return _observedInput;
      }
      set
      {
        __isset.observedInput = true;
        this._observedInput = value;
      }
    }

    public bool FullSnapshot
    {
      get
      {
        return _fullSnapshot;
      }
      set
      {
        __isset.fullSnapshot = true;
        this._fullSnapshot = value;
      }
    }

    public List<EntityWarpSpec> EntityState
    {
      get
      {
        return _entityState;
      }
      set
      {
        __isset.entityState = true;
        this._entityState = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool chefs;
      public bool items;
      public bool serverMessages;
      public bool entityRegistry;
      public bool lastFramePaused;
      public bool nextFramePaused;
      public bool frameNumber;
      public bool invalidStateReason;
      public bool physicsFramesElapsed;
      public bool framesSinceLastNoPhysicsFrame;
      public bool roundTimeSeconds;
      public bool roundTimeRemainingSeconds;
      public bool episodeId;
      public bool episodeStep;
      public bool inEpisode;
      public bool episodeStart;
      public bool episodeEnd;
      public bool episodeEndReason;
      public bool gameState;
      public bool levelName;
      public bool observedInput;
      public bool fullSnapshot;
      public bool entityState;
    }

    public OutputData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Map) {
                {
                  Chefs = new Dictionary<int, ChefSpecificData>();
                  TMap _map16 = iprot.ReadMapBegin();
                  for( int _i17 = 0; _i17 < _map16.Count; ++_i17)
                  {
                    int _key18;
                    ChefSpecificData _val19;
                    _key18 = iprot.ReadI32();
                    _val19 = new ChefSpecificData();
                    _val19.Read(iprot);
                    Chefs[_key18] = _val19;
                  }
                  iprot.ReadMapEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Map) {
                {
                  Items = new Dictionary<int, ItemData>();
                  TMap _map20 = iprot.ReadMapBegin();
                  for( int _i21 = 0; _i21 < _map20.Count; ++_i21)
                  {
                    int _key22;
                    ItemData _val23;
                    _key22 = iprot.ReadI32();
                    _val23 = new ItemData();
                    _val23.Read(iprot);
                    Items[_key22] = _val23;
                  }
                  iprot.ReadMapEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.List) {
                {
                  ServerMessages = new List<ServerMessage>();
                  TList _list24 = iprot.ReadListBegin();
                  for( int _i25 = 0; _i25 < _list24.Count; ++_i25)
                  {
                    ServerMessage _elem26;
                    _elem26 = new ServerMessage();
                    _elem26.Read(iprot);
                    ServerMessages.Add(_elem26);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.List) {
                {
                  EntityRegistry = new List<EntityRegistryData>();
                  TList _list27 = iprot.ReadListBegin();
                  for( int _i28 = 0; _i28 < _list27.Count; ++_i28)
                  {
                    EntityRegistryData _elem29;
                    _elem29 = new EntityRegistryData();
                    _elem29.Read(iprot);
                    EntityRegistry.Add(_elem29);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.Bool) {
                LastFramePaused = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 7:
              if (field.Type == TType.Bool) {
                NextFramePaused = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 8:
              if (field.Type == TType.I32) {
                FrameNumber = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 9:
              if (field.Type == TType.String) {
                InvalidStateReason = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 10:
              if (field.Type == TType.I32) {
                PhysicsFramesElapsed = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 11:
              if (field.Type == TType.I32) {
                FramesSinceLastNoPhysicsFrame = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 12:
              if (field.Type == TType.Double) {
                RoundTimeSeconds = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 13:
              if (field.Type == TType.Double) {
                RoundTimeRemainingSeconds = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 14:
              if (field.Type == TType.I32) {
                EpisodeId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 15:
              if (field.Type == TType.I32) {
                EpisodeStep = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 16:
              if (field.Type == TType.Bool) {
                InEpisode = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 17:
              if (field.Type == TType.Bool) {
                EpisodeStart = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 18:
              if (field.Type == TType.Bool) {
                EpisodeEnd = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 19:
              if (field.Type == TType.String) {
                EpisodeEndReason = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 20:
              if (field.Type == TType.String) {
                GameState = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 21:
              if (field.Type == TType.String) {
                LevelName = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 22:
              if (field.Type == TType.Map) {
                {
                  ObservedInput = new Dictionary<int, OneInputData>();
                  TMap _map34 = iprot.ReadMapBegin();
                  for( int _i35 = 0; _i35 < _map34.Count; ++_i35)
                  {
                    int _key36;
                    OneInputData _val37;
                    _key36 = iprot.ReadI32();
                    _val37 = new OneInputData();
                    _val37.Read(iprot);
                    ObservedInput[_key36] = _val37;
                  }
                  iprot.ReadMapEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 23:
              if (field.Type == TType.Bool) {
                FullSnapshot = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 24:
              if (field.Type == TType.List) {
                {
                  EntityState = new List<EntityWarpSpec>();
                  TList _list39 = iprot.ReadListBegin();
                  for( int _i40 = 0; _i40 < _list39.Count; ++_i40)
                  {
                    EntityWarpSpec _elem41;
                    _elem41 = new EntityWarpSpec();
                    _elem41.Read(iprot);
                    EntityState.Add(_elem41);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("OutputData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Chefs != null && __isset.chefs) {
          field.Name = "chefs";
          field.Type = TType.Map;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, Chefs.Count));
            foreach (int _iter30 in Chefs.Keys)
            {
              oprot.WriteI32(_iter30);
              Chefs[_iter30].Write(oprot);
            }
            oprot.WriteMapEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (Items != null && __isset.items) {
          field.Name = "items";
          field.Type = TType.Map;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, Items.Count));
            foreach (int _iter31 in Items.Keys)
            {
              oprot.WriteI32(_iter31);
              Items[_iter31].Write(oprot);
            }
            oprot.WriteMapEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (ServerMessages != null && __isset.serverMessages) {
          field.Name = "serverMessages";
          field.Type = TType.List;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, ServerMessages.Count));
            foreach (ServerMessage _iter32 in ServerMessages)
            {
              _iter32.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (EntityRegistry != null && __isset.entityRegistry) {
          field.Name = "entityRegistry";
          field.Type = TType.List;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, EntityRegistry.Count));
            foreach (EntityRegistryData _iter33 in EntityRegistry)
            {
              _iter33.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (__isset.lastFramePaused) {
          field.Name = "lastFramePaused";
          field.Type = TType.Bool;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(LastFramePaused);
          oprot.WriteFieldEnd();
        }
        if (__isset.nextFramePaused) {
          field.Name = "nextFramePaused";
          field.Type = TType.Bool;
          field.ID = 7;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(NextFramePaused);
          oprot.WriteFieldEnd();
        }
        if (__isset.frameNumber) {
          field.Name = "frameNumber";
          field.Type = TType.I32;
          field.ID = 8;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(FrameNumber);
          oprot.WriteFieldEnd();
        }
        if (InvalidStateReason != null && __isset.invalidStateReason) {
          field.Name = "invalidStateReason";
          field.Type = TType.String;
          field.ID = 9;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(InvalidStateReason);
          oprot.WriteFieldEnd();
        }
        if (__isset.physicsFramesElapsed) {
          field.Name = "physicsFramesElapsed";
          field.Type = TType.I32;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(PhysicsFramesElapsed);
          oprot.WriteFieldEnd();
        }
        if (__isset.framesSinceLastNoPhysicsFrame) {
          field.Name = "framesSinceLastNoPhysicsFrame";
          field.Type = TType.I32;
          field.ID = 11;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(FramesSinceLastNoPhysicsFrame);
          oprot.WriteFieldEnd();
        }
        if (__isset.roundTimeSeconds) {
          field.Name = "roundTimeSeconds";
          field.Type = TType.Double;
          field.ID = 12;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(RoundTimeSeconds);
          oprot.WriteFieldEnd();
        }
        if (__isset.roundTimeRemainingSeconds) {
          field.Name = "roundTimeRemainingSeconds";
          field.Type = TType.Double;
          field.ID = 13;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(RoundTimeRemainingSeconds);
          oprot.WriteFieldEnd();
        }
        if (__isset.episodeId) {
          field.Name = "episodeId";
          field.Type = TType.I32;
          field.ID = 14;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(EpisodeId);
          oprot.WriteFieldEnd();
        }
        if (__isset.episodeStep) {
          field.Name = "episodeStep";
          field.Type = TType.I32;
          field.ID = 15;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(EpisodeStep);
          oprot.WriteFieldEnd();
        }
        if (__isset.inEpisode) {
          field.Name = "inEpisode";
          field.Type = TType.Bool;
          field.ID = 16;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(InEpisode);
          oprot.WriteFieldEnd();
        }
        if (__isset.episodeStart) {
          field.Name = "episodeStart";
          field.Type = TType.Bool;
          field.ID = 17;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(EpisodeStart);
          oprot.WriteFieldEnd();
        }
        if (__isset.episodeEnd) {
          field.Name = "episodeEnd";
          field.Type = TType.Bool;
          field.ID = 18;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(EpisodeEnd);
          oprot.WriteFieldEnd();
        }
        if (EpisodeEndReason != null && __isset.episodeEndReason) {
          field.Name = "episodeEndReason";
          field.Type = TType.String;
          field.ID = 19;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(EpisodeEndReason);
          oprot.WriteFieldEnd();
        }
        if (GameState != null && __isset.gameState) {
          field.Name = "gameState";
          field.Type = TType.String;
          field.ID = 20;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(GameState);
          oprot.WriteFieldEnd();
        }
        if (LevelName != null && __isset.levelName) {
          field.Name = "levelName";
          field.Type = TType.String;
          field.ID = 21;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(LevelName);
          oprot.WriteFieldEnd();
        }
        if (ObservedInput != null && __isset.observedInput) {
          field.Name = "observedInput";
          field.Type = TType.Map;
          field.ID = 22;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, ObservedInput.Count));
            foreach (int _iter38 in ObservedInput.Keys)
            {
              oprot.WriteI32(_iter38);
              ObservedInput[_iter38].Write(oprot);
            }
            oprot.WriteMapEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (__isset.fullSnapshot) {
          field.Name = "fullSnapshot";
          field.Type = TType.Bool;
          field.ID = 23;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(FullSnapshot);
          oprot.WriteFieldEnd();
        }
        if (EntityState != null && __isset.entityState) {
          field.Name = "entityState";
          field.Type = TType.List;
          field.ID = 24;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, EntityState.Count));
            foreach (EntityWarpSpec _iter42 in EntityState)
            {
              _iter42.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("OutputData(");
      bool __first = true;
      if (Chefs != null && __isset.chefs) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Chefs: ");
        __sb.Append(Chefs);
      }
      if (Items != null && __isset.items) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Items: ");
        __sb.Append(Items);
      }
      if (ServerMessages != null && __isset.serverMessages) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ServerMessages: ");
        __sb.Append(ServerMessages);
      }
      if (EntityRegistry != null && __isset.entityRegistry) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EntityRegistry: ");
        __sb.Append(EntityRegistry);
      }
      if (__isset.lastFramePaused) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LastFramePaused: ");
        __sb.Append(LastFramePaused);
      }
      if (__isset.nextFramePaused) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NextFramePaused: ");
        __sb.Append(NextFramePaused);
      }
      if (__isset.frameNumber) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("FrameNumber: ");
        __sb.Append(FrameNumber);
      }
      if (InvalidStateReason != null && __isset.invalidStateReason) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("InvalidStateReason: ");
        __sb.Append(InvalidStateReason);
      }
      if (__isset.physicsFramesElapsed) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PhysicsFramesElapsed: ");
        __sb.Append(PhysicsFramesElapsed);
      }
      if (__isset.framesSinceLastNoPhysicsFrame) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("FramesSinceLastNoPhysicsFrame: ");
        __sb.Append(FramesSinceLastNoPhysicsFrame);
      }
      if (__isset.roundTimeSeconds) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RoundTimeSeconds: ");
        __sb.Append(RoundTimeSeconds);
      }
      if (__isset.roundTimeRemainingSeconds) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RoundTimeRemainingSeconds: ");
        __sb.Append(RoundTimeRemainingSeconds);
      }
      if (__isset.episodeId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EpisodeId: ");
        __sb.Append(EpisodeId);
      }
      if (__isset.episodeStep) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EpisodeStep: ");
        __sb.Append(EpisodeStep);
      }
      if (__isset.inEpisode) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("InEpisode: ");
        __sb.Append(InEpisode);
      }
      if (__isset.episodeStart) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EpisodeStart: ");
        __sb.Append(EpisodeStart);
      }
      if (__isset.episodeEnd) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EpisodeEnd: ");
        __sb.Append(EpisodeEnd);
      }
      if (EpisodeEndReason != null && __isset.episodeEndReason) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EpisodeEndReason: ");
        __sb.Append(EpisodeEndReason);
      }
      if (GameState != null && __isset.gameState) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("GameState: ");
        __sb.Append(GameState);
      }
      if (LevelName != null && __isset.levelName) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LevelName: ");
        __sb.Append(LevelName);
      }
      if (ObservedInput != null && __isset.observedInput) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ObservedInput: ");
        __sb.Append(ObservedInput);
      }
      if (__isset.fullSnapshot) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("FullSnapshot: ");
        __sb.Append(FullSnapshot);
      }
      if (EntityState != null && __isset.entityState) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EntityState: ");
        __sb.Append(EntityState);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
