/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class PlatePendingReturnData : TBase
  {
    private int _returnStationEntityId;
    private double _timer;

    public int ReturnStationEntityId
    {
      get
      {
        return _returnStationEntityId;
      }
      set
      {
        __isset.returnStationEntityId = true;
        this._returnStationEntityId = value;
      }
    }

    public double Timer
    {
      get
      {
        return _timer;
      }
      set
      {
        __isset.timer = true;
        this._timer = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool returnStationEntityId;
      public bool timer;
    }

    public PlatePendingReturnData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                ReturnStationEntityId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Double) {
                Timer = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("PlatePendingReturnData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.returnStationEntityId) {
          field.Name = "returnStationEntityId";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ReturnStationEntityId);
          oprot.WriteFieldEnd();
        }
        if (__isset.timer) {
          field.Name = "timer";
          field.Type = TType.Double;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(Timer);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("PlatePendingReturnData(");
      bool __first = true;
      if (__isset.returnStationEntityId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ReturnStationEntityId: ");
        __sb.Append(ReturnStationEntityId);
      }
      if (__isset.timer) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Timer: ");
        __sb.Append(Timer);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
