/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class PlateReturnControllerWarpData : TBase
  {
    private List<PlatePendingReturnData> _plates;

    public List<PlatePendingReturnData> Plates
    {
      get
      {
        return _plates;
      }
      set
      {
        __isset.plates = true;
        this._plates = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool plates;
    }

    public PlateReturnControllerWarpData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  Plates = new List<PlatePendingReturnData>();
                  TList _list46 = iprot.ReadListBegin();
                  for( int _i47 = 0; _i47 < _list46.Count; ++_i47)
                  {
                    PlatePendingReturnData _elem48;
                    _elem48 = new PlatePendingReturnData();
                    _elem48.Read(iprot);
                    Plates.Add(_elem48);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("PlateReturnControllerWarpData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Plates != null && __isset.plates) {
          field.Name = "plates";
          field.Type = TType.List;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, Plates.Count));
            foreach (PlatePendingReturnData _iter49 in Plates)
            {
              _iter49.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("PlateReturnControllerWarpData(");
      bool __first = true;
      if (Plates != null && __isset.plates) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Plates: ");
        __sb.Append(Plates);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
