/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class StackWarpData : TBase
  {
    private List<EntityIdOrRef> _stackContents;

    public List<EntityIdOrRef> StackContents
    {
      get
      {
        return _stackContents;
      }
      set
      {
        __isset.stackContents = true;
        this._stackContents = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool stackContents;
    }

    public StackWarpData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  StackContents = new List<EntityIdOrRef>();
                  TList _list50 = iprot.ReadListBegin();
                  for( int _i51 = 0; _i51 < _list50.Count; ++_i51)
                  {
                    EntityIdOrRef _elem52;
                    _elem52 = new EntityIdOrRef();
                    _elem52.Read(iprot);
                    StackContents.Add(_elem52);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("StackWarpData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (StackContents != null && __isset.stackContents) {
          field.Name = "stackContents";
          field.Type = TType.List;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, StackContents.Count));
            foreach (EntityIdOrRef _iter53 in StackContents)
            {
              _iter53.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("StackWarpData(");
      bool __first = true;
      if (StackContents != null && __isset.stackContents) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("StackContents: ");
        __sb.Append(StackContents);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
