/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ThrowableItemWarpData : TBase
  {
    private bool _isFlying;
    private double _flightTimer;
    private int _throwerEntityId;
    private List<ColliderRef> _throwStartColliders;

    public bool IsFlying
    {
      get
      {
        return _isFlying;
      }
      set
      {
        __isset.isFlying = true;
        this._isFlying = value;
      }
    }

    public double FlightTimer
    {
      get
      {
        return _flightTimer;
      }
      set
      {
        __isset.flightTimer = true;
        this._flightTimer = value;
      }
    }

    public int ThrowerEntityId
    {
      get
      {
        return _throwerEntityId;
      }
      set
      {
        __isset.throwerEntityId = true;
        this._throwerEntityId = value;
      }
    }

    public List<ColliderRef> ThrowStartColliders
    {
      get
      {
        return _throwStartColliders;
      }
      set
      {
        __isset.throwStartColliders = true;
        this._throwStartColliders = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool isFlying;
      public bool flightTimer;
      public bool throwerEntityId;
      public bool throwStartColliders;
    }

    public ThrowableItemWarpData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool) {
                IsFlying = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Double) {
                FlightTimer = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                ThrowerEntityId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.List) {
                {
                  ThrowStartColliders = new List<ColliderRef>();
                  TList _list42 = iprot.ReadListBegin();
                  for( int _i43 = 0; _i43 < _list42.Count; ++_i43)
                  {
                    ColliderRef _elem44;
                    _elem44 = new ColliderRef();
                    _elem44.Read(iprot);
                    ThrowStartColliders.Add(_elem44);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ThrowableItemWarpData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.isFlying) {
          field.Name = "isFlying";
          field.Type = TType.Bool;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(IsFlying);
          oprot.WriteFieldEnd();
        }
        if (__isset.flightTimer) {
          field.Name = "flightTimer";
          field.Type = TType.Double;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(FlightTimer);
          oprot.WriteFieldEnd();
        }
        if (__isset.throwerEntityId) {
          field.Name = "throwerEntityId";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ThrowerEntityId);
          oprot.WriteFieldEnd();
        }
        if (ThrowStartColliders != null && __isset.throwStartColliders) {
          field.Name = "throwStartColliders";
          field.Type = TType.List;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, ThrowStartColliders.Count));
            foreach (ColliderRef _iter45 in ThrowStartColliders)
            {
              _iter45.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ThrowableItemWarpData(");
      bool __first = true;
      if (__isset.isFlying) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IsFlying: ");
        __sb.Append(IsFlying);
      }
      if (__isset.flightTimer) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("FlightTimer: ");
        __sb.Append(FlightTimer);
      }
      if (__isset.throwerEntityId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ThrowerEntityId: ");
        __sb.Append(ThrowerEntityId);
      }
      if (ThrowStartColliders != null && __isset.throwStartColliders) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ThrowStartColliders: ");
        __sb.Append(ThrowStartColliders);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
