/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class WarpSpec : TBase
  {
    private List<EntityWarpSpec> _entities;
    private List<int> _entitiesToDelete;
    private int _frame;
    private string _invalidStateReason;

    public List<EntityWarpSpec> Entities
    {
      get
      {
        return _entities;
      }
      set
      {
        __isset.entities = true;
        this._entities = value;
      }
    }

    public List<int> EntitiesToDelete
    {
      get
      {
        return _entitiesToDelete;
      }
      set
      {
        __isset.entitiesToDelete = true;
        this._entitiesToDelete = value;
      }
    }

    public int Frame
    {
      get
      {
        return _frame;
      }
      set
      {
        __isset.frame = true;
        this._frame = value;
      }
    }

    public string InvalidStateReason
    {
      get
      {
        return _invalidStateReason;
      }
      set
      {
        __isset.invalidStateReason = true;
        this._invalidStateReason = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool entities;
      public bool entitiesToDelete;
      public bool frame;
      public bool invalidStateReason;
    }

    public WarpSpec() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  Entities = new List<EntityWarpSpec>();
                  TList _list62 = iprot.ReadListBegin();
                  for( int _i63 = 0; _i63 < _list62.Count; ++_i63)
                  {
                    EntityWarpSpec _elem64;
                    _elem64 = new EntityWarpSpec();
                    _elem64.Read(iprot);
                    Entities.Add(_elem64);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  EntitiesToDelete = new List<int>();
                  TList _list65 = iprot.ReadListBegin();
                  for( int _i66 = 0; _i66 < _list65.Count; ++_i66)
                  {
                    int _elem67;
                    _elem67 = iprot.ReadI32();
                    EntitiesToDelete.Add(_elem67);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                Frame = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                InvalidStateReason = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("WarpSpec");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Entities != null && __isset.entities) {
          field.Name = "entities";
          field.Type = TType.List;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, Entities.Count));
            foreach (EntityWarpSpec _iter68 in Entities)
            {
              _iter68.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (EntitiesToDelete != null && __isset.entitiesToDelete) {
          field.Name = "entitiesToDelete";
          field.Type = TType.List;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.I32, EntitiesToDelete.Count));
            foreach (int _iter69 in EntitiesToDelete)
            {
              oprot.WriteI32(_iter69);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (__isset.frame) {
          field.Name = "frame";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Frame);
          oprot.WriteFieldEnd();
        }
        if (InvalidStateReason != null && __isset.invalidStateReason) {
          field.Name = "invalidStateReason";
          field.Type = TType.String;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(InvalidStateReason);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("WarpSpec(");
      bool __first = true;
      if (Entities != null && __isset.entities) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Entities: ");
        __sb.Append(Entities);
      }
      if (EntitiesToDelete != null && __isset.entitiesToDelete) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EntitiesToDelete: ");
        __sb.Append(EntitiesToDelete);
      }
      if (__isset.frame) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Frame: ");
        __sb.Append(Frame);
      }
      if (InvalidStateReason != null && __isset.invalidStateReason) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("InvalidStateReason: ");
        __sb.Append(InvalidStateReason);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
