/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class WorkableItemWarpData : TBase
  {
    private int _progress;
    private int _subProgress;
    private bool _onWorkstation;

    public int Progress
    {
      get
      {
        return _progress;
      }
      set
      {
        __isset.progress = true;
        this._progress = value;
      }
    }

    public int SubProgress
    {
      get
      {
        return _subProgress;
      }
      set
      {
        __isset.subProgress = true;
        this._subProgress = value;
      }
    }

    public bool OnWorkstation
    {
      get
      {
        return _onWorkstation;
      }
      set
      {
        __isset.onWorkstation = true;
        this._onWorkstation = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool progress;
      public bool subProgress;
      public bool onWorkstation;
    }

    public WorkableItemWarpData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                Progress = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                SubProgress = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Bool) {
                OnWorkstation = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("WorkableItemWarpData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.progress) {
          field.Name = "progress";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Progress);
          oprot.WriteFieldEnd();
        }
        if (__isset.subProgress) {
          field.Name = "subProgress";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(SubProgress);
          oprot.WriteFieldEnd();
        }
        if (__isset.onWorkstation) {
          field.Name = "onWorkstation";
          field.Type = TType.Bool;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(OnWorkstation);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("WorkableItemWarpData(");
      bool __first = true;
      if (__isset.progress) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Progress: ");
        __sb.Append(Progress);
      }
      if (__isset.subProgress) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("SubProgress: ");
        __sb.Append(SubProgress);
      }
      if (__isset.onWorkstation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("OnWorkstation: ");
        __sb.Append(OnWorkstation);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
