/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class WorkstationInteracterWarpData : TBase
  {
    private int _chefEntityId;
    private double _actionTimer;

    public int ChefEntityId
    {
      get
      {
        return _chefEntityId;
      }
      set
      {
        __isset.chefEntityId = true;
        this._chefEntityId = value;
      }
    }

    public double ActionTimer
    {
      get
      {
        return _actionTimer;
      }
      set
      {
        __isset.actionTimer = true;
        this._actionTimer = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool chefEntityId;
      public bool actionTimer;
    }

    public WorkstationInteracterWarpData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                ChefEntityId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.Double) {
                ActionTimer = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("WorkstationInteracterWarpData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.chefEntityId) {
          field.Name = "chefEntityId";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ChefEntityId);
          oprot.WriteFieldEnd();
        }
        if (__isset.actionTimer) {
          field.Name = "actionTimer";
          field.Type = TType.Double;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(ActionTimer);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("WorkstationInteracterWarpData(");
      bool __first = true;
      if (__isset.chefEntityId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ChefEntityId: ");
        __sb.Append(ChefEntityId);
      }
      if (__isset.actionTimer) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ActionTimer: ");
        __sb.Append(ActionTimer);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
