/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hpmv
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class WorkstationWarpData : TBase
  {
    private List<WorkstationInteracterWarpData> _interacters;
    private EntityIdOrRef _item;

    public List<WorkstationInteracterWarpData> Interacters
    {
      get
      {
        return _interacters;
      }
      set
      {
        __isset.interacters = true;
        this._interacters = value;
      }
    }

    public EntityIdOrRef Item
    {
      get
      {
        return _item;
      }
      set
      {
        __isset.item = true;
        this._item = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool interacters;
      public bool item;
    }

    public WorkstationWarpData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  Interacters = new List<WorkstationInteracterWarpData>();
                  TList _list38 = iprot.ReadListBegin();
                  for( int _i39 = 0; _i39 < _list38.Count; ++_i39)
                  {
                    WorkstationInteracterWarpData _elem40;
                    _elem40 = new WorkstationInteracterWarpData();
                    _elem40.Read(iprot);
                    Interacters.Add(_elem40);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                Item = new EntityIdOrRef();
                Item.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("WorkstationWarpData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Interacters != null && __isset.interacters) {
          field.Name = "interacters";
          field.Type = TType.List;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, Interacters.Count));
            foreach (WorkstationInteracterWarpData _iter41 in Interacters)
            {
              _iter41.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (Item != null && __isset.item) {
          field.Name = "item";
          field.Type = TType.Struct;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          Item.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("WorkstationWarpData(");
      bool __first = true;
      if (Interacters != null && __isset.interacters) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Interacters: ");
        __sb.Append(Interacters);
      }
      if (Item != null && __isset.item) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Item: ");
        __sb.Append(Item== null ? "<null>" : Item.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
